### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [shimabahramnejad/prj-rev-bwfs-dasmoto#6]
https://github.com/shimabahramnejad/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtCraft/resources/css/style.css#L10-L41

There's a lot of repetition here. Use more general selectors in order to consolidate common/shared styles.

Consider using the universal selector `*` to apply a style by default to every element and remove the repeated styles from the rest of your CSS rules.

```css
* {
  font-family: Helvetica;
}

h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

.brush {
  background-color:mediumspringgreen;
}
```
